/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bhos.qa.labs;

import org.junit.Test;
import static org.junit.Assert.*;


public class AppTest {

    PermissionManager prm= new PermissionManager();

    @Test
    public void testGet() {
        assertEquals("User", prm.getPermissionLevel());
    }

    @Test
    public void testSet() {
        prm.setPermissionLevel(PermissionLevel.DEVELOPER);
        assertEquals("Developer", prm.getPermissionLevel());
    }
}
