/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bhos.qa.labs;

public class Classroom {

    String name;
    int student_count;
    int enter_year;
    int uni_years;
    String average_class_score;
    int semester_lesson_count;

    public Classroom (String name, int student_count, int enter_year, int uni_years, String average_class_score, int semester_lesson_count){
        this.name = name;
        this.student_count = student_count;
        this.enter_year = enter_year;
        this.uni_years = uni_years;
        this.average_class_score = average_class_score;
        this.semester_lesson_count = semester_lesson_count;
    }

    public String getName(){
        return this.name;
    }

    public int getStudentCount(){
        return this.student_count;
    }

    public int getEnterYear(){
        return this.enter_year;
    }

    public int getUniYears(){
        return this.uni_years;
    }

    public String getAvg(){
        return this.average_class_score;
    }

    public int get2SemesterLessonCount(){
        return this.semester_lesson_count;
    }

    public int getGraduationDate(){
        return this.enter_year + this.uni_years;
    }

    public int getAllYearLessonCount(){
        return this.semester_lesson_count*this.uni_years;
    }

    public void CountNewStudentNumber(int left_student_count){
        this.student_count = this.student_count - left_student_count;
    }

    public String getClassWithYear(){
        return this.name + " - " + this.enter_year;
    }

    public static void main(String[] args) {
        Classroom class1 = new Classroom("IT", 25, 2018, 5, "B", 11);
        System.out.println(class1.getName());
        System.out.println(class1.getStudentCount());
        System.out.println(class1.getEnterYear());
        System.out.println(class1.getUniYears());
        System.out.println(class1.getAvg());
        System.out.println(class1.get2SemesterLessonCount());
        System.out.println(class1.getGraduationDate());
        System.out.println(class1.getAllYearLessonCount());
        class1.CountNewStudentNumber(3);
        System.out.println(class1.getStudentCount());
        System.out.println(class1.getClassWithYear());
    }
}