/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_test;

public class CompareStrings {
    public String compare(String a, String b) {
        
        int len_a = a.length();
        int len_b = b.length();

        if (len_a < len_b){
          return "the first word is smaller than the second word";  
        }
        else if (len_a > len_b){
            return "the first word is longer than the second word";
        }
        else{
            return "the first word is equal to the second word";
        }
    }

    public static void main(String[] args) {
        CompareStrings for_comparison = new CompareStrings();
        System.out.println(for_comparison.compare("24354","secnd"));
    }
}
