/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_test;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void stringsAreEqual() {
        CompareStrings toTest = new CompareStrings();
        System.out.println(toTest.compare("first456456_to_test_1","second_to_test_2"));
    }
}
